#tasks file for pycharm
---
- name: Add PPA for PyCharm
  become: yes
  apt_repository:
    repo: "{{ pycharm_ppa }}"

- name: Install PyCharm
  become: yes
  apt:
    name: pycharm-community
    state: installed
